name: insta_picker
description: Instagram Picker.
version: 0.0.9+12
homepage: https://github.com/mstrkn/InstaPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^2.2.0
  permission_handler: ^11.3.1
  visibility_detector: ^0.4.0+2
  just_the_tooltip: ^0.0.12
  path_provider: ^2.1.2
  video_trimmer: ^3.0.1
  photo_manager: ^3.0.0
  image_cropper: ^5.0.1
  video_player: ^2.8.4
  photo_view: ^0.14.0
  fluttertoast: ^8.2.4
  provider: ^6.1.2
  camera: ^0.10.5+9
  platform: ^3.1.4
  chewie: ^1.8.1
  logger: ^2.2.0
  path: ^1.9.0

  photofilters:
    git:
      url: https://github.com/noeGnh/photofilters.git
      ref: develop

  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

flutter:
