name: insta_picker
description: Instagram Picker.
version: 0.0.8+2
homepage: https://github.com/mstrkn/InstaPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^1.1.0
  permission_handler: ^8.3.0
  visibility_detector: ^0.2.2
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.8
  video_trimmer: ^1.0.0
  super_tooltip: ^1.0.1
  photo_manager: ^1.3.10
  image_cropper: ^1.4.1
  video_player: ^2.2.9
  photo_view: ^0.13.0
  fluttertoast: ^8.0.8
  provider: ^6.0.1
  camera: ^0.9.4+5
  chewie: ^1.2.2
  logger: ^1.1.0
  path: ^1.8.1

  photofilters:
    git:
      url: https://github.com/mstrkn/photofilters.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  provider: ^6.0.1
  path: ^1.8.1

flutter:
