name: insta_picker
description: Instagram Picker.
version: 0.0.9+12
homepage: https://github.com/mstrkn/InstaPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.0
  visibility_detector: ^0.4.0+2
  get_thumbnail_video: ^0.7.3
  just_the_tooltip: ^0.0.12
  path_provider: ^2.1.5
  video_trimmer: ^5.0.0
  photo_manager: ^3.6.4
  image_cropper: ^9.1.0
  video_player: ^2.9.5
  photo_view: ^0.15.0
  fluttertoast: ^8.2.12
  provider: ^6.1.5
  camera: ^0.11.1
  platform: ^3.1.6
  chewie: ^1.11.3
  logger: ^2.5.0
  path: ^1.9.1

  photofilters:
    git:
      url: git@github.com:noeGnh/photofilters.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
