name: insta_picker
description: Instagram Picker.
version: 0.0.3
author: Arkane<mstrkn@gmail.com>
homepage: https://github.com/mstrkn/InstaPicker.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_better_camera: ^0.6.1
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.24
  super_tooltip: ^0.9.6
  photo_manager: ^0.5.8
  image_cropper: ^1.3.1
  video_player: ^1.0.1
  torch_compat: ^1.0.2
  fluttertoast: ^7.1.1
  photo_view: ^0.10.3
  provider: ^4.3.2+2
  chewie: ^0.12.0
  path: ^1.7.0

  photofilters:
    git:
      url: git@github.com:mstrkn/photofilters.git

  video_trimmer:
    git:
      url: git@github.com:mstrkn/video_trimmer.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
