name: insta_picker
description: Instagram Picker.
version: 0.0.9+10
homepage: https://github.com/mstrkn/InstaPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^1.1.3
  permission_handler: ^10.2.0
  visibility_detector: ^0.4.0+2
  just_the_tooltip: ^0.0.12
  path_provider: ^2.0.14
  video_trimmer: ^1.2.0
  photo_manager: ^2.6.0
  image_cropper: ^3.0.3
  video_player: ^2.6.1
  photo_view: ^0.14.0
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  camera: ^0.10.4
  platform: ^3.1.0
  chewie: ^1.4.0
  logger: ^1.3.0
  path: ^1.8.3

  photofilters:
    git:
      url: https://github.com/mstrkn/photofilters.git
      ref: develop

  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  path: ^1.8.3
  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

flutter:
