name: insta_picker
description: Instagram Picker.
version: 0.0.7
author: Arkane<mstrkn@gmail.com>
homepage: https://github.com/mstrkn/InstaPicker.git
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^1.0.0
  permission_handler: ^6.1.1
  visibility_detector: ^0.2.0
  video_thumbnail: ^0.3.3
  path_provider: ^2.0.1
  video_trimmer: ^0.4.0
  super_tooltip: ^1.0.1
  photo_manager: ^1.1.1
  image_cropper: ^1.4.0
  video_player: ^2.1.1
  photo_view: ^0.11.1
  fluttertoast: ^8.0.3
  provider: ^5.0.0
  camera: ^0.8.1
  chewie: ^1.0.0
  logger: ^1.0.0
  path: ^1.8.0

  photofilters:
    git:
      url: https://github.com/mstrkn/photofilters.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
