name: insta_picker
description: Instagram Picker.
version: 0.0.2
author: Arkane<mstrkn@gmail.com>
homepage: https://github.com/mstrkn/InstaPicker.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_better_camera: ^0.6.1
  better_player: ^0.0.34
  path_provider: ^1.6.24
  super_tooltip: ^0.9.6
  photo_manager: ^0.5.8
  image_cropper: ^1.3.1
  video_player: ^1.0.1
  torch_compat: ^1.0.2
  fluttertoast: ^7.1.1
  photo_view: ^0.10.3
  provider: ^4.3.2+2
  path: ^1.7.0

  photofilters:
    git:
      url: git@github.com:mstrkn/photofilters.git

  video_trimmer:
    git:
      url: git@github.com:mstrkn/video_trimmer.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
