name: insta_picker
description: Instagram Picker.
version: 0.0.8+5
homepage: https://github.com/mstrkn/InstaPicker.git
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^1.1.0
  permission_handler: ^10.0.0
  visibility_detector: ^0.3.3
  path_provider: ^2.0.11
  video_trimmer: ^1.1.3
  super_tooltip: ^1.0.1
  photo_manager: ^2.1.4
  image_cropper: ^2.0.3
  video_player: ^2.4.5
  photo_view: ^0.14.0
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  camera: ^0.10.0
  platform: ^3.1.0
  chewie: ^1.3.4
  logger: ^1.1.0
  path: ^1.8.2

  photofilters:
    git:
      url: https://github.com/mstrkn/photofilters.git
      ref: develop

  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  path: ^1.8.2
  video_thumbnail:
    git:
      url: https://github.com/julek-kal/video_thumbnail
      ref: 734a2d5

flutter:
