name: insta_picker
description: Instagram Picker.
version: 0.0.6
author: Arkane<mstrkn@gmail.com>
homepage: https://github.com/mstrkn/InstaPicker.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^0.7.0
  permission_handler: ^5.1.0+2
  visibility_detector: ^0.1.5
  video_thumbnail: ^0.2.5+1
  path_provider: ^1.6.27
  super_tooltip: ^0.9.6
  photo_manager: ^0.5.8
  image_cropper: ^1.3.1
  video_player: ^1.0.1
  torch_compat: ^1.0.2
  fluttertoast: ^7.1.6
  photo_view: ^0.10.3
  provider: ^4.3.3
  camera: ^0.7.0+2
  chewie: ^0.12.2
  logger: ^0.9.4
  path: ^1.7.0

  photofilters:
    git:
      url: git@github.com:mstrkn/photofilters.git

  video_trimmer:
    git:
      url: git@github.com:mstrkn/video_trimmer.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
